#!/usr/bin/env bash
set -o errexit
set -o nounset

files="$(mktemp)"
world=Amonkhet
ip=149.56.241.69
target_dir=~/Library/ApplicationSupport/minecraft/WolffDen_server

# remove temporary files on exit
clean_up() { rm -f "$files" "${world}.zip"; }
trap clean_up EXIT

# download all schematics
builtin cd "${target_dir}"
ftp ${ip} <<< 'ls plugins/WorldEdit/schematics' | grep -oE '[a-zA-Z]+.schem' > "${files}"
for file in $(cat "${files}"); do
  ftp ${ip} <<< $'cd plugins/WorldEdit/schematics\nget '"${file}"
done
echo 'downloaded all schematics!'

# download map itself
echo "downloading map..."
ftp ${ip} <<< "get $world.zip"
mv "${world}.zip" "${world}_$(date '+%Y-%m-%d').zip"

echo 'backup complete!'