#!/bin/bash
set -e

git_loc=$HOME/github/personal
scripts=$HOME/.scripts

# temporary files for files that will have redactions
moss=$(mktemp)
message=$(mktemp)
cleaned_rc=$(mktemp)
timestamp=$(date '+%Y-%m-%d')
clean_up() { rm $moss $message $cleaned_rc; }
trap clean_up EXIT

check_rc() {
  builtin cd zsh/
  perl -pe 's$(?<=webhook/alexa/).*(?=/)$<HOOK_ID>$g' $HOME/.zshrc > $cleaned_rc
  if ! diff -q $cleaned_rc personal.zshrc &>/dev/null; then
    # check if the RC files are different, aside from the webhooks
    cp $cleaned_rc personal.zshrc
  fi
  builtin cd ..
}

check_scripts() {
  builtin cd scripts/
  perl -pe 's/(?<=$userid=)[0-9]+;/; # get ur own >:(/g' $scripts/moss > $moss
  perl -pe 's/.*\).*recipient=.*;;/\tname)\trecipient="+123456789"/g;
  			    s/(?<=email=).*/ # TODO: your imessage email/g' $scripts/message > $message
  for s in $scripts/*; do
  	f=${s#$scripts/}
  	# handle redacted files differently
    if [[ $f = 'moss' || $f = 'message' ]]; then
      eval "diff $`echo $f` $f &>/dev/null || cp $`echo $f` $f"
    else
      diff -q $scripts/$f $f &>/dev/null || cp $scripts/$f .
    fi
  done
  builtin cd ..
}

update_repo() {
  git add --all
  git stash
  git pull origin master
  git stash pop
  git add --all
  scripts=$(for f in $(git status --porcelain | sed 's/^...//'); do echo -n "-m '$f' "; done)
  git commit -m "$timestamp -- backed up .zshrc && scripts" $scripts
  git push -u origin master &>/dev/null
}

backup_history() {
  git clone git@github.com:MatthewWolff/private.git
  cp $HOME/.zsh_history private/
  builtin cd $_
  git add .zsh_history
  git commit -m "$timestamp - backed up zsh history"
  git push -u origin master &>/dev/null
  builtin cd ..
  rm -rf private/
}

main() {
  builtin cd $git_loc
  git pull origin master >/dev/null

  check_rc
  check_scripts
  update_repo

  backup_history
}

main && exit 0
