#!/bin/bash
set -e -x

PDF=MatthewWolffResume.pdf
CODE=MatthewWolffResume.zip
LOC=~/Downloads

[[ -f $LOC/$PDF ]] && [[ -f $LOC/$CODE ]]  # must exist

# move files
cd ~/Desktop/college/resume
FILE_NUM=$(ls -1 resume_pdfs/ | tail -n1 | grep -oE "[0-9]+")
VERSION=$(($FILE_NUM - 4))

mv $LOC/$PDF $LOC/$CODE .
# clear out old
rm -r gitresume/LaTeX/* &>/dev/null || true
rm -r gitresume/LaTeX/.[a-zA-Z0-9]* &>/dev/null || true
# replace
unzip $CODE -d gitresume/LaTeX/ && rm $CODE
cp $PDF gitresume/pdf/$VERSION.pdf
cp $PDF resume_pdfs/$(($FILE_NUM + 1))
# commit
cd gitresume
git add --all
git commit -m "version $VERSION"
git push -u origin master

# for f in `ls -1 *latex.zip`; do 
# 	file_num="0$((10#${f:0:2}-5))"
# 	file_pdf=${f:0:2}.pdf
# 	new_pdf=gitresume/pdf/$file_num.pdf

# 	rm -r gitresume/LaTeX/* &>/dev/null || true
# 	rm -r gitresume/LaTeX/.[a-zA-Z0-9]* &>/dev/null || true
# 	unzip $f -d gitresume/LaTeX/
# 	cp $file_pdf $new_pdf
# 	rm $f
# 	cd gitresume
# 	git add .
# 	git commit -m "version $file_num" 
# 	cd ..
# done
# cd gitresume && git push -u origin master
# exit 0
