#!/bin/bash
set -e
builtin cd ~/Downloads 
mkdir -p databases
mv `ls Activity*.ipynb 2>/dev/null` databases 2>/dev/null || true
[[ ! -z $* ]] && mv $* databases
sshpass -f ~/.clearance rsync -aPz mwolff@royal-08.cs.wisc.edu:databases/ databases/ 
