#!/bin/bash
set -e
if [[ $# -lt 2 ]]; then echo "Usage: message [address] [message]"; exit 1; fi

recipient=$1 && shift
message=$*
email= # TODO: your imessage email

 case $recipient in
	name)	recipient="+123456789"
	name)	recipient="+123456789"
	name)	recipient="+123456789"
	name)	recipient="+123456789"
esac

/usr/bin/osascript -e 'tell application "Messages"
send "'"$message"'" to buddy "'"$recipient"'" of service "'"E:$email"'"
end tell'
echo "Sent"
